name: Update XMLTV Channel IDs

on:
  schedule:
    # Runs at 2 AM UTC every day
    - cron: "0 2 * * *"
  # Optional: Allow manual trigger
  workflow_dispatch:

jobs:
  update-xmltv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install fast-xml-parser

      - name: Run XMLTV update script
        run: bun run modifier.ts

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push if changed
        run: |
          if git diff --quiet updated_epg.xml.gz; then
            echo "No changes to commit"
          else
            git add updated_epg.xml.gz
            git commit -m "Update XMLTV channel mappings [automated]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: xmltv-epg
          path: updated_epg.xml.gz
          retention-days: 7
